// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpuBX76zBhrfGghYMUWIt5QY76TvNXE18',
    appId: '1:340760487910:web:9d159184678d7d95155827',
    messagingSenderId: '340760487910',
    projectId: 'dima-server',
    authDomain: 'dima-server.firebaseapp.com',
    storageBucket: 'dima-server.appspot.com',
    measurementId: 'G-3R47N6QBNL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRmnoO5ggrqhfyj6q8ZMKLdPrQOIkv8S8',
    appId: '1:340760487910:android:000e54931b995ef6155827',
    messagingSenderId: '340760487910',
    projectId: 'dima-server',
    storageBucket: 'dima-server.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnx1YnxQpVtA9mq6eBJMSvUeX8cExiYIM',
    appId: '1:340760487910:ios:6077dea98938ac57155827',
    messagingSenderId: '340760487910',
    projectId: 'dima-server',
    storageBucket: 'dima-server.appspot.com',
    iosClientId: '340760487910-rnvc0qd9p29ge9nbmld3biicm4oqd9ho.apps.googleusercontent.com',
    iosBundleId: 'com.example.pro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnx1YnxQpVtA9mq6eBJMSvUeX8cExiYIM',
    appId: '1:340760487910:ios:6077dea98938ac57155827',
    messagingSenderId: '340760487910',
    projectId: 'dima-server',
    storageBucket: 'dima-server.appspot.com',
    iosClientId: '340760487910-rnvc0qd9p29ge9nbmld3biicm4oqd9ho.apps.googleusercontent.com',
    iosBundleId: 'com.example.pro',
  );
}
